<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc0b7d85bc3512fa0696b0e974fb8822f
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc0b7d85bc3512fa0696b0e974fb8822f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc0b7d85bc3512fa0696b0e974fb8822f::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
